export const Strings = {
  entry: 'Entrar',
  loginRequired: 'Digite o CPF',
  passwordRequired: 'Digite a senha',
  login: 'CPF',
  password: 'Senha',
  schemaValidationCpfCnpj: 'CPF inválido.',
  forgotPassord: 'Esqueci a senha?',
  buttonLogin: 'Entrar',
  falhaRequest: 'Serviço indisponível no momento. Tente novamente mais tarde',
  headersHistory: [
    'Nome',
    'CPF',
    'Data',
    'Hora',
    'Especialidade',
    'Especialista',
    'Unidade',
    'Status'
  ],
  headersHistoryResponse: [
    'patient',
    'cpf',
    'newDate',
    'newTime',
    'specialist_name',
    'specialty',
    'unit',
    'appointment_status'
  ],
  headersUnits: ['CNPJ', 'Nome', 'Telefone', 'E-mail', 'CEP', 'Endereço'],
  headersUnitsResponse: [
    'cnpj',
    'name',
    'phone_primary',
    'email',
    'zip_code',
    'street'
  ],
  headersUsers: ['Nome', 'CPF', 'Telefone', 'E-mail', 'Status'],
  headersUsersResponse: [
    'name',
    'cpf',
    'phone_primary',
    'email',
    'profile',
    'status'
  ],
  headersSpecialist: [
    'Nome',
    'CPF',
    'Telefone',
    'E-mail',
    'Especialidade',
    'Status'
  ],
  headersSpecialistResponse: [
    'name',
    'cpf',
    'phone_primary',
    'email',
    'specialties',
    'status'
  ],
  headersPatient: ['Nome', 'CPF', 'Nascimento', 'Telefone', 'E-mail', 'Status'],
  headersPatientsResponse: [
    'name',
    'cpf',
    'birthday',
    'phone_primary',
    'email',
    'status'
  ],
  headersNewRole: ['Description', 'Status'],
  headersScale: ['Especialista', 'Unidade'],
  headersSpecialty: ['Descrição', 'Status'],
  headersScaleResponse: ['name', 'unit'],
  schedule: 'Agendamento',
  description: 'Descrição',
  pacient: 'Paciente',
  speciality: 'Especialidade',
  pluralSpeciality: 'Especialidades',
  specialist: 'Especialista',
  date: 'Data',
  hour: 'Hora',
  observation: 'Observação',
  descriptionRequired: 'Descrição é obrigatório',
  pacientRequired: 'Paciente é obrigatório',
  specialityRequired: 'Especialidade é obrigatório',
  specialistRequired: 'Especialista é obrigatório',
  dateRequired: 'Data é obrigatório',
  hourRequired: 'Hora é obrigatório',
  save: 'Salvar',
  cancel: 'Cancelar',
  edit: 'Editar',
  goBack: 'Voltar',
  insertUnit: 'Cadastrar Unidade',
  insertUser: 'Cadastrar Usuário',
  insertSpecialist: 'Cadastrar Especialista',
  updateSpecialist: 'Atualizar Especialista',
  updateUnit: 'Atualizar Unidade',
  updatePatient: 'Atualizar Paciente',
  updateSpecialty: 'Atualizar Especialidade',
  updateRole: 'Atualizar Perfil',
  insertPatient: 'Cadastrar Paciente',
  insertSpecialty: 'Cadastrar Especialidade',
  insertRole: 'Cadastrar Perfil',
  editUnit: 'Editar Unidade',
  viewDataUser: 'Dados do Usuário',
  myData: 'Meus Dados',
  search: 'Pesquisar',
  scheduleConfirmation: 'Confirmação de Agenda',
  selectSpecialist: 'Selecione o Especialista',
  schemaRequiredInitialHour: 'Hora inicial é obrigatório',
  schemaRequiredFinalHour: 'Hora final é obrigatório',
  schemaRequiredInterval: 'Intervalo é obrigatório',
  timeOfAttendance: ['15 minutos', '30 minutos', '45 minutos', '1 hora'],
  placeholderCNJP: 'CNPJ',
  placeholderCPF: 'CPF',
  placeholderName: 'Nome',
  placeholderResponsable: 'Responsável',
  placeholderProfile: 'Perfil',
  placeholderPhonePrimay: 'Telefone Principal',
  placeholderPhoneSecondary: 'Telefone Secundário',
  placeholderLatitude: 'Latitude',
  placeholderLongitude: 'Longitude',
  placeholderEmail: 'E-mail',
  placeholderZipCode: 'CEP',
  placeholderStreet: 'Logradouro',
  placeholderBlock: 'Quadra',
  placeholderLot: 'Lote',
  placeholderNumber: 'Número',
  placeholderNeighborhood: 'Bairro',
  placeholderCity: 'Cidade',
  placeholderState: 'Estado',
  placeholderComplement: 'Complemento',
  placeholderLinkFacebook: 'Link do Facebook',
  placeholderLinkInstagram: 'Link do Instagram',
  placeholderLinkSite: 'Link do Site',
  schemaRequiredCnpj: 'CNPJ é obrigatório',
  schemaNameRequired: 'Nome é obrigatório',
  schemaResponsibleRequired: 'Responsável é obrigatório',
  schemaEmailRequired: 'E-mail é obrigatório',
  schemaStateRequired: 'Estado é obrigatório',
  schemaCityRequired: 'Cidade é obrigatório',
  schemaPhonePrimaryRequired: 'Telefone Principal é obrigatório',
  schemaLatitudeRequired: 'Latitude é obrigatório',
  schemaLongitudeRequired: 'Longitude é obrigatório',
  schemaZipCodeRequired: 'CEP é obrigatório',
  schemaStreetRequired: 'Logradouro é obrigatório',
  schemaNumberRequired: 'Número é obrigatório',
  confirmation: 'Confirmação',
  whatDoYouWantToDo: 'O que você deseja fazer?',
  close: 'Fechar',
  messageSuccessInsertUnit: 'O cadastro da unidade foi realizada com sucesso.',
  messageSuccessInsertUser: 'O cadastro do usuário foi realizada com sucesso.',
  messageSuccessInsertSpecialist:
    'O cadastro do especialista foi realizada com sucesso.',
  messageSuccessInsertPatient:
    'O cadastro do paciente foi realizada com sucesso.',
  messageSuccessInsertScaleSchedule:
    'O cadastro da escala foi realizada com sucesso.',
  messageSuccessInsertSpecialty:
    'O cadastro da especialidade foi realizado com sucesso.',
  messageSuccessInsertRole: 'O cadastro do perfil foi realizado com sucesso.',
  messageSuccessUpdateUnit: 'O cadastro da unidade foi atualizado com sucesso.',
  messageSuccessUpdateUser: 'O cadastro do usuário foi atualizado com sucesso.',
  messageSuccessUpdateSpecialist:
    'O cadastro do especialista foi atualizado com sucesso.',
  messageSuccessUpdatePatient:
    'O cadastro do paciente foi atualizado com sucesso.',
  messageSuccessUpdateSpecialty:
    'O cadastro da especialidade foi atualizado com sucesso.',
  messageSuccessUpdateRole: 'O cadastro do perfil foi atualizado com sucesso.',
  selectDate: 'Selecione a data',
  hoursDisponibles: 'Horários disponíveis',
  resetPasswordSpecialist: 'Redefinir Senha do Especialista',
  resetPasswordUser: 'Redefinir Senha do Usuário',
  resetPasswordPatient: 'Redefinir Senha do Paciente',
  status: 'Status',
  linkedUnits: 'Unidades Vinculadas',
  headersResponseNewSpecialties: ['description', 'status'],
  erase: 'Excluir',
  notInformed: 'Não Informado'
};
