export const Strings = {
  entry: 'Entrar',
  loginRequired: 'Digite o CPF',
  passwordRequired: 'Digite a senha',
  login: 'CPF',
  password: 'Senha',
  schemaValidationCpfCnpj: 'CPF inválido.',
  forgotPassord: 'Esqueci a senha?',
  buttonLogin: 'Entrar',
  falhaRequest: 'Serviço indisponível no momento. Tente novamente mais tarde',
  headersHistory: [
    'Nome',
    'CPF',
    'Data',
    'Hora',
    'Especialidade',
    'Especialista',
    'Unidade'
  ],
  headersUnits: ['CNPJ', 'Nome', 'Telefone', 'E-mail', 'CEP', 'Endereço'],
  schedule: 'Agendamento',
  description: 'Descrição',
  pacient: 'Paciente',
  speciality: 'Especialidade',
  specialist: 'Especialista',
  date: 'Data',
  hour: 'Hora',
  observation: 'Observação',
  descriptionRequired: 'Descrição é obrigatório',
  pacientRequired: 'Paciente é obrigatório',
  specialityRequired: 'Especialidade é obrigatório',
  specialistRequired: 'Especialista é obrigatório',
  dateRequired: 'Data é obrigatório',
  hourRequired: 'Hora é obrigatório',
  save: 'Salvar',
  cancel: 'Cancelar',
  inserUnit: 'Cadastrar Unidade'
};
